import type { Metadata } from 'next'

//does not rerender, applies to all pages

export const metadata: Metadata = {
  title: 'Photosynthesis',
  description: 'Generated by create-next-app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}